### ISSUE TITLE
routereflector:v0.5.0 contains incorrect confd version

### ISSUE THREAD

**Issue by 2ffs2nns** [projectcalico/routereflector#6]
Looks like the routereflector:v0.5.0 image contains a incorrect version of confd

```
 docker run --rm quay.io/calico/routereflector:v0.5.0 /confd --version
confd v1.0.0-beta1-4-g4619952
```

I was expecting `v1.0.0` or ` v0.12.1-calico-0.4.3`

**Comment by nelljerram** [comment]
@2ffs2nns It would indeed be neater if, whenever we release confd, we also re-release calico/routereflector with that confd.  On the other hand, 3.0.x testing has reported that calico/routereflector works, even though we haven't done that.  What that means in practice, I believe, is that there have not been any libcalico-go changes, between the libcalico-go used by  https://github.com/projectcalico/confd/commit/4619952a4f847ed5978093b8b2a7fa9e2b8f3f3d and that used by https://github.com/projectcalico/confd/commit/0dcaece56235c6ea452f18d9b729864ed12c0ff4, that incompatibly affect the subset of the Calico data model that the RR relies upon.

**Comment by caseydavenport** [comment]
I think we're saying there's nothing we should do here, and for the next RR release it would be nice to get an "official" tagged release of calico/confd into this image.

**Comment by 2ffs2nns** [comment]
+1 thanks @caseydavenport

**Comment by JoshuaAndrew** [comment]
+1 thanks @caseydavenport
