### ISSUE TITLE
 RR  run as a global peer but it does not works well when I use calico/routereflector:v0.5.0

### ISSUE THREAD

**Issue by JoshuaAndrew** [projectcalico/routereflector#7]
RR  run as a global peer but it does not works well when I use calico/routereflector:v0.5.0

@neiljerram  @djlwilder

## Expected Behavior
IPv4 BGP status
+---------------+-------------------+-------+----------+--------------------------------+
| PEER ADDRESS  |     PEER TYPE     | STATE |  SINCE   |              INFO              |
+---------------+-------------------+-------+----------+--------------------------------+
| 192.168.1.238 | global            | up| 10:11:58 | Established                          |
| 192.168.1.239 | global            | up| 10:12:50 | Established                          |
+---------------+-------------------+-------+----------+--------------------------------+

## Current Behavior
IPv4 BGP status
+---------------+-------------------+-------+----------+--------------------------------+
| PEER ADDRESS  |     PEER TYPE     | STATE |  SINCE   |              INFO              |
+---------------+-------------------+-------+----------+--------------------------------+
| 192.168.1.238 | global            | start | 10:11:58 | Active Socket: Connection      |
|               |                   |       |          | refused                        |
| 192.168.1.239 | global            | start | 10:12:50 | Active Socket: Connection      |
|               |                   |       |          | refused                        |
+---------------+-------------------+-------+----------+--------------------------------+

root@calico-rr-1:~# cat  /var/log/calico/bird/current 
2018-02-09_10:11:14.31990 bird: **_Unable to open configuration file /config/bird.cfg: No such file or directory_**
2018-02-09_10:11:15.27271 bird: Graceful restart started
2018-02-09_10:11:15.27274 bird: Graceful restart done
2018-02-09_10:11:15.27275 bird: Started

**_I don't have this problem when I use calico/routereflector:v0.4.2_**

## Possible Solution

        N/A      
   

## Steps to Reproduce (for bugs)

1.  deploy calico router reflector
docker run --privileged --net=host -d                              \
           -e IP=<IPv4_RR>                                         \
           [-e IP6=<IPv6_RR>]                                      \
           -e ETCD_ENDPOINTS=<https://ETCD_IP:PORT>                \
           -v <FULL_PATH_TO_CERT_DIR>:<MOUNT_DIR>                  \
           -e ETCD_CA_CERT_FILE=<MOUNT_DIR>/<CA_FILE>              \
           -e ETCD_CERT_FILE=<MOUNT_DIR>/<CERT_FILE>               \
           -e ETCD_KEY_FILE=<MOUNT_DIR>/<KEY_FILE>                 \
           calico/routereflector:v0.5.0
2.  setup etcd config
etcdctl set calico/bgp/v1/rr_v4/192.168.1.238 "{\"ip\":\"192.168.1.238\",\"cluster_id\":\"172.31.0.0\"}"
3. setup bgpPeer
calicoctl create -f - << EOF
apiVersion: v1
kind: bgpPeer
metadata:
  peerIP: 192.168.1.238
  scope: global
spec:
  asNumber: 64512
EOF

## Your Environment

* calico/routereflector version:

           calico/routereflector:v0.5.0

* Operating System and version:
[root@calico-rr-2 ~]# cat /etc/os-release 
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"
CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"

[root@calico-rr-2 ~]# uname -a
Linux calico-rr-2 3.10.0-514.el7.x86_64 #1 SMP Tue Nov 22 16:42:41 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

**Comment by neiljerram** [comment]
@JoshuaAndrew What are the peers here?  I guess they are Calico nodes.  If that's right, can you let me know which calico/node version?

**Comment by caseydavenport** [comment]
IIUC `calico/routereflector:v0.5.0` is only supposed to work with Calico v3.0, right @neiljerram?

At least according to the releases page: https://docs.projectcalico.org/v2.6/releases/

**Comment by neiljerram** [comment]
So @JoshuaAndrew you should use RR v0.4.2 with calico/node 2.x, and RR v0.5.0 with calico/node 3.x. Other combinations are not expected to work.

Given that, is there anything else that we need to cover in this issue, or can we close this issue now?

**Comment by JoshuaAndrew** [comment]
@neiljerram @caseydavenport 
I will use RR v0.4.2 with calico/node 2.x
Happy new year，Thanks a lot！

**Comment by neiljerram** [comment]
Thanks @JoshuaAndrew, and happy new year to you too!
